
using System.Collections.Generic;

namespace Glitch9.AIDevKit.Editor
{
    /// <summary>
    /// Hard-coded data for model capabilities.
    /// </summary>
    internal static class Metadata_ModelFeatures
    {
        internal static Dictionary<string, ModelFeature> Map = new() {
            { "01-ai/yi-large", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming },
            { "aetherwing/mn-starcannon-12b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming },
            { "ai21/jamba-1.5-large", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "ai21/jamba-1.5-mini", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "ai21/jamba-1.6-large", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "ai21/jamba-1.6-mini", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "ai21/jamba-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "alfredbros/codellama-7b-instruct-solidity", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "allenai/molmo-7b-d:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "all-hands/openhands-lm-32b-v0.1", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "alpindale/goliath-120b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "anthracite-org/magnum-v2-72b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "anthropic/claude-2", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-2.0", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-2.0:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-2.1", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-2.1:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3-haiku", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3-haiku:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3-opus", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3-opus:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3-sonnet", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3-sonnet:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.5-haiku", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.5-haiku:20241022", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.5-haiku:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.5-sonnet-20240620", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.5-sonnet-20240620:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.7", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.7-sonnet", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.7-sonnet:beta", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "anthropic/claude-3.7-sonnet:thinking", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "agentica-org/deepcoder-14b-preview:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cohere/command", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cohere/command-r", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cohere/command-r-03-2024", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cohere/command-r-08-2024", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cohere/command-r7b-12-2024", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cohere/command-r-plus", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cohere/command-r-plus-04-2024", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cognitivecomputations/dolphin-mixtral-8x22b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cognitivecomputations/dolphin3.0-r1-mistral-24b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "cognitivecomputations/dolphin3.0-r1-mistral-24b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-chat-v3-0324", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-chat-v3-0324:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-prover-v2", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-prover-v2:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-distill-llama-70b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-distill-llama-70b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-distill-llama-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-distill-qwen-14b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-distill-qwen-14b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-distill-qwen-32b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-distill-qwen-32b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1-zero:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-r1", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "deepset/deepseek-v3-base:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "eleutherai/llemma_7b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "eva-unit-01/eva-llama-3.33-70b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "eva-unit-01/eva-qwen-2.5-72b", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "featherless/qwerky-72b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "google/gemini-2.0-flash-001", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-2.0-flash-exp:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-2.0-flash-lite-001", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-2.5-flash-preview", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-2.5-flash-preview:thinking", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-2.5-pro-preview-03-25", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-3-12b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-3-12b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-3-1b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-3-1b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-3-27b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-3-27b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-flash-1.5", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-flash-1.5-8b", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-flash-1.5-8b-exp", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-pro-1.5", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemini-pro-vision", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-2-27b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-2-27b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-2-9b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-2-9b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-3-12b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-3-12b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-3-1b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-3-1b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-3-27b-it", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/gemma-3-27b-it:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/learnlm-1.5-pro-experimental:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/palm-2-chat-bison", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/palm-2-chat-bison-32k", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/palm-2-codechat-bison", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "google/palm-2-codechat-bison-32k", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "huggingfaceh4/zephyr-7b-beta:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "inflection/inflection-3-pi", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "inflection/inflection-3-productivity", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "latitudegames/wayfarer-large-70b-llama-3.3", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "liquid/lfm-3b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "liquid/lfm-40b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "liquid/lfm-7b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mancer/weaver", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-2-70b-chat", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.1-405b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.1-405b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.1-405b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.1-70b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.1-8b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.1-8b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.3-70b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.3-70b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-11b-vision-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-11b-vision-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-1b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-1b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-3b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-3b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-90b-vision-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-3.2-90b-vision-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-4-maverick", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-4-maverick:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-4-scout", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-4-scout:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-guard-3-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "meta-llama/llama-guard-4-12b", ModelFeature.FineTuning },
            { "microsoft/mai-ds-r1:free", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "microsoft/phi-3.5-mini-128k-instruct", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "microsoft/phi-4", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "microsoft/phi-4-multimodal-instruct", ModelFeature.TextGeneration | ModelFeature.Streaming | ModelFeature.SpeechRecognition},
            { "microsoft/wizardlm-2-8x22b", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "minimax/minimax-01", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "mistral/ministral-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/codestral-2501", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/codestral-mamba", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/ministral-3b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-3b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-7b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-7b-instruct-v0.1", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-7b-instruct-v0.2", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-7b-instruct-v0.3", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-7b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-large-2407", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "mistralai/mistral-large-2411", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "mistralai/mistral-medium", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-nemo", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-nemo:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-saba", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "mistralai/mistral-small", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-small-24b-instruct-2501", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-small-24b-instruct-2501:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-small-3.1-24b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-small-3.1-24b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/mistral-tiny", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/pixtral-12b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "mistralai/pixtral-large-2411", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "moonshotai/kimi-vl-a3b-thinking:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "moonshotai/moonlight-16b-a3b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "neversleep/llama-3.1-lumimaid-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nothingisreal/mn-celeste-12b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nousresearch/deephermes-3-llama-3.1-8b-preview", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nousresearch/hermes-2-pro-llama-3-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nousresearch/hermes-3-llama-3.1-405b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nousresearch/hermes-3-llama-3.1-70b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nousresearch/nous-hermes-2-mixtral-8x7b-dpo", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nvidia/llama-3.1-nemotron-70b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nvidia/llama-3.1-nemotron-ultra-253b-v1:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nvidia/llama-3.3-nemotron-super-49b-v1", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "nvidia/llama-3.3-nemotron-super-49b-v1:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "open-r1/olympiccoder-32b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "openai/chatgpt-4o-latest", ModelFeature.TextGeneration | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-3.5-turbo", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-3.5-turbo-0125", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/gpt-3.5-turbo-1106", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-3.5-turbo-16k", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-3.5-turbo-instruct", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/gpt-4", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4-0314", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/gpt-4-1106-preview", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4-32k", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4-32k-0314", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/gpt-4-turbo", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4-turbo-preview", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4.1", ModelFeature.TextGeneration | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4.1-mini", ModelFeature.TextGeneration | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4.1-nano", ModelFeature.TextGeneration | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4.5-preview", ModelFeature.TextGeneration | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4o", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4o-2024-08-06", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4o-2024-11-20", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "openai/gpt-4o-mini", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4o-mini-2024-07-18", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling},
            { "openai/gpt-4o-search-preview", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.FunctionCalling | ModelFeature.Search},
            { "openai/o1", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/o1-preview", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/o1-preview-2024-09-12", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/o1-pro", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/o3", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/o3-mini-high", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/o4-mini", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "openai/o4-mini-high", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "opengvlab/internvl3-14b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "opengvlab/internvl3-2b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "openrouter/auto", ModelFeature.TextGeneration | ModelFeature.Streaming},
            { "perplexity/llama-3.1-sonar-large-128k-online", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.Search},
            { "perplexity/llama-3.1-sonar-small-128k-online", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.Search},
            { "perplexity/r1-1776", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "perplexity/sonar", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "perplexity/sonar-deep-research", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.Search},
            { "perplexity/sonar-pro", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.Search},
            { "perplexity/sonar-reasoning", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "perplexity/sonar-reasoning-pro", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming | ModelFeature.Search},
            { "pygmalionai/mythalion-13b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2-72b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-72b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-72b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-7b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-7b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-vl-72b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-vl-72b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-vl-7b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-2.5-vl-7b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-turbo", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-vl-max", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen-vl-plus", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen2.5-coder-7b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen2.5-vl-32b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen2.5-vl-32b-instruct:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-0.6b-04-28:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-1.7b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-14b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-14b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-235b-a22b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-235b-a22b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-30b-a3b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-30b-a3b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-32b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-32b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-4b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwen3-8b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwq-32b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwq-32b-preview", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "qwen/qwq-32b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "rekai/reka-flash-3:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "sao10k/l3-euryale-70b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "sao10k/l3-lunaris-8b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "sao10k/l3.3-euryale-70b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "scb10x/llama3.1-typhoon2-70b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "scb10x/llama3.1-typhoon2-8b-instruct", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "shisa-ai/shisa-v2-llama3.3-70b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "sophosympatheia/midnight-rose-70b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "steelskull/l3.3-electra-r1-70b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thedrummer/anubis-pro-105b-v1", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thedrummer/rocinante-12b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thedrummer/skyfall-36b-v2", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thudm/glm-4-32b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thudm/glm-4-32b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thudm/glm-z1-32b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thudm/glm-z1-32b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thudm/glm-z1-9b:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "thudm/glm-z1-rumination-32b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "tngtech/deepseek-r1t-chimera:free", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "undi95/remm-slerp-l2-13b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "undi95/toppy-m-7b", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "x-ai/grok-2-1212", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "x-ai/grok-2-vision-1212", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "x-ai/grok-3-beta", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "x-ai/grok-3-mini-beta", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming},
            { "x-ai/grok-beta", ModelFeature.TextGeneration | ModelFeature.FineTuning | ModelFeature.Streaming}
        };
    }
}